CREATE TABLE IF NOT EXISTS POSTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Author TEXT NOT NULL,
    Date TEXT NOT NULL,
    Title TEXT NOT NULL,
    Content TEXT NOT NULL
                                );

CREATE TABLE IF NOT EXISTS COMMENTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PostID INTEGER NOT NULL,
    ParentID INTEGER DEFAULT NULL,
    Author TEXT NOT NULL,
    Date TEXT NOT NULL,
    Content TEXT NOT NULL,

    FOREIGN KEY (PostID) REFERENCES POSTS(ID),
    FOREIGN KEY (ParentID) REFERENCES COMMENTS(ID)
                                );
